### ISSUE TITLE
Some test case can not pass

### ISSUE THREAD

**Issue by ChopperLee2011** [fny/node-firebase-rest#1]
After I run `npm test`, it throws errors, One of the error messages is:
```
1) FirebaseREST.Client #get returns a Fetch.Response
  Message:
    ypeError: Cannot read property 'replace' of undefined
  Stack:
    TypeError: Cannot read property 'replace' of undefined
        at Object.urlFor [as default] (/Users/chopper/GitHub/node-firebase-rest/dist/FirebaseREST/helpers/urlFor.js:16:23)
        at Client.request (/Users/chopper/GitHub/node-firebase-rest/dist/FirebaseREST/Client.js:120:38)
        at Client.put (/Users/chopper/GitHub/node-firebase-rest/dist/FirebaseREST/Client.js:64:21)
        at Object.<anonymous> (/Users/chopper/GitHub/node-firebase-rest/spec/FirebaseREST/ClientSpec.js:14:14)
```

**Comment by ChopperLee2011** [comment]
My bad, I do not setup FIREBASE_URL and FIREBASE_SECRER well
